// DEFINE DIALOG
#define DIALOG_REGISTER_VERTIFIKASI 1
#define DIALOG_REGISTER_PASSWORD 2
#define DIALOG_REGISTER_DATE 3
#define DIALOG_REGISTER_TINGGI 4
#define DIALOG_REGISTER_BERAT 5
#define DIALOG_LOGIN 6
#define DIALOG_UNUSED 7